//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vividl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vividl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to AVI.
        /// </summary>
        public static string DownloadOption_AVI {
            get {
                return ResourceManager.GetString("DownloadOption_AVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Direct Download.
        /// </summary>
        public static string DownloadOption_Best {
            get {
                return ResourceManager.GetString("DownloadOption_Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to M4A.
        /// </summary>
        public static string DownloadOption_M4A {
            get {
                return ResourceManager.GetString("DownloadOption_M4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge to MKV.
        /// </summary>
        public static string DownloadOption_MKV {
            get {
                return ResourceManager.GetString("DownloadOption_MKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to MP3.
        /// </summary>
        public static string DownloadOption_MP3 {
            get {
                return ResourceManager.GetString("DownloadOption_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to MP4.
        /// </summary>
        public static string DownloadOption_MP4 {
            get {
                return ResourceManager.GetString("DownloadOption_MP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Ogg Vorbis.
        /// </summary>
        public static string DownloadOption_Vorbis {
            get {
                return ResourceManager.GetString("DownloadOption_Vorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to WAV.
        /// </summary>
        public static string DownloadOption_WAV {
            get {
                return ResourceManager.GetString("DownloadOption_WAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to WebM.
        /// </summary>
        public static string DownloadOption_Webm {
            get {
                return ResourceManager.GetString("DownloadOption_Webm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Output.
        /// </summary>
        public static string DownloadOutputWindow_ClearOutput {
            get {
                return ResourceManager.GetString("DownloadOutputWindow_ClearOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Output.
        /// </summary>
        public static string DownloadOutputWindow_CopyOutput {
            get {
                return ResourceManager.GetString("DownloadOutputWindow_CopyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Output.
        /// </summary>
        public static string DownloadOutputWindow_Title {
            get {
                return ResourceManager.GetString("DownloadOutputWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Format.
        /// </summary>
        public static string FetchWindow_DownloadFormat {
            get {
                return ResourceManager.GetString("FetchWindow_DownloadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download playlist if available.
        /// </summary>
        public static string FetchWindow_DownloadPlaylist {
            get {
                return ResourceManager.GetString("FetchWindow_DownloadPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Video URLs in separate lines.
        /// </summary>
        public static string FetchWindow_EnterUrls {
            get {
                return ResourceManager.GetString("FetchWindow_EnterUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download immediately.
        /// </summary>
        public static string FetchWindow_ImmediateDownload {
            get {
                return ResourceManager.GetString("FetchWindow_ImmediateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string FetchWindow_Options {
            get {
                return ResourceManager.GetString("FetchWindow_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string FetchWindow_Password {
            get {
                return ResourceManager.GetString("FetchWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string FetchWindow_Settings {
            get {
                return ResourceManager.GetString("FetchWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string FetchWindow_TabAuthentication {
            get {
                return ResourceManager.GetString("FetchWindow_TabAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string FetchWindow_TabGeneral {
            get {
                return ResourceManager.GetString("FetchWindow_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string FetchWindow_Username {
            get {
                return ResourceManager.GetString("FetchWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Password.
        /// </summary>
        public static string FetchWindow_VideoPassword {
            get {
                return ResourceManager.GetString("FetchWindow_VideoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video has already been fetched to the download list.
        ///To allow duplicates, go to Options -&gt; Settings..
        /// </summary>
        public static string MainWindow_AlreadyFetched {
            get {
                return ResourceManager.GetString("MainWindow_AlreadyFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching {0} videos failed:.
        /// </summary>
        public static string MainWindow_CountFailedFetches {
            get {
                return ResourceManager.GetString("MainWindow_CountFailedFetches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Folder.
        /// </summary>
        public static string MainWindow_DownloadFolder {
            get {
                return ResourceManager.GetString("MainWindow_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure the given URL is valid..
        /// </summary>
        public static string MainWindow_FetchFailed_General {
            get {
                return ResourceManager.GetString("MainWindow_FetchFailed_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch video.
        /// </summary>
        public static string MainWindow_FetchFailed_Title {
            get {
                return ResourceManager.GetString("MainWindow_FetchFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainWindow_HeaderFile {
            get {
                return ResourceManager.GetString("MainWindow_HeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MainWindow_HeaderOptions {
            get {
                return ResourceManager.GetString("MainWindow_HeaderOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Videos.
        /// </summary>
        public static string MainWindow_HeaderVideos {
            get {
                return ResourceManager.GetString("MainWindow_HeaderVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new videos by pasting or importing URLs..
        /// </summary>
        public static string MainWindow_ListEmpty {
            get {
                return ResourceManager.GetString("MainWindow_ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MainWindow_MenuAbout {
            get {
                return ResourceManager.GetString("MainWindow_MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add New Videos.
        /// </summary>
        public static string MainWindow_MenuAdd {
            get {
                return ResourceManager.GetString("MainWindow_MenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel All Downloads.
        /// </summary>
        public static string MainWindow_MenuCancelAll {
            get {
                return ResourceManager.GetString("MainWindow_MenuCancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear Download List.
        /// </summary>
        public static string MainWindow_MenuClearList {
            get {
                return ResourceManager.GetString("MainWindow_MenuClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Download All Videos.
        /// </summary>
        public static string MainWindow_MenuDownloadAll {
            get {
                return ResourceManager.GetString("MainWindow_MenuDownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MainWindow_MenuExit {
            get {
                return ResourceManager.GetString("MainWindow_MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export Video Links.
        /// </summary>
        public static string MainWindow_MenuExport {
            get {
                return ResourceManager.GetString("MainWindow_MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import Video Links.
        /// </summary>
        public static string MainWindow_MenuImport {
            get {
                return ResourceManager.GetString("MainWindow_MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Output Window.
        /// </summary>
        public static string MainWindow_MenuOutputWindow {
            get {
                return ResourceManager.GetString("MainWindow_MenuOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste Video Link.
        /// </summary>
        public static string MainWindow_MenuPaste {
            get {
                return ResourceManager.GetString("MainWindow_MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string MainWindow_MenuRemove {
            get {
                return ResourceManager.GetString("MainWindow_MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All _Finished Downloads.
        /// </summary>
        public static string MainWindow_MenuRemoveFinished {
            get {
                return ResourceManager.GetString("MainWindow_MenuRemoveFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All _Unavailable Downloads.
        /// </summary>
        public static string MainWindow_MenuRemoveUnavailable {
            get {
                return ResourceManager.GetString("MainWindow_MenuRemoveUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Download _Folder....
        /// </summary>
        public static string MainWindow_MenuSelectFolder {
            get {
                return ResourceManager.GetString("MainWindow_MenuSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MainWindow_MenuSettings {
            get {
                return ResourceManager.GetString("MainWindow_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainWindow_OpenFolder {
            get {
                return ResourceManager.GetString("MainWindow_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed:.
        /// </summary>
        public static string MainWindow_StatusFailed {
            get {
                return ResourceManager.GetString("MainWindow_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Process:.
        /// </summary>
        public static string MainWindow_StatusInProcess {
            get {
                return ResourceManager.GetString("MainWindow_StatusInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful:.
        /// </summary>
        public static string MainWindow_StatusSucceeded {
            get {
                return ResourceManager.GetString("MainWindow_StatusSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator:.
        /// </summary>
        public static string MetadataWindow_Creator {
            get {
                return ResourceManager.GetString("MetadataWindow_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MetadataWindow_Description {
            get {
                return ResourceManager.GetString("MetadataWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string MetadataWindow_Details {
            get {
                return ResourceManager.GetString("MetadataWindow_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string MetadataWindow_Duration {
            get {
                return ResourceManager.GetString("MetadataWindow_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string MetadataWindow_Link {
            get {
                return ResourceManager.GetString("MetadataWindow_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string MetadataWindow_Source {
            get {
                return ResourceManager.GetString("MetadataWindow_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded:.
        /// </summary>
        public static string MetadataWindow_UploadDate {
            get {
                return ResourceManager.GetString("MetadataWindow_UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader:.
        /// </summary>
        public static string MetadataWindow_Uploader {
            get {
                return ResourceManager.GetString("MetadataWindow_Uploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views:.
        /// </summary>
        public static string MetadataWindow_Views {
            get {
                return ResourceManager.GetString("MetadataWindow_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string PathSelectionControl_Change {
            get {
                return ResourceManager.GetString("PathSelectionControl_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Playlist URL.
        /// </summary>
        public static string PlaylistEntry_CopyUrl {
            get {
                return ResourceManager.GetString("PlaylistEntry_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory where the downloaded videos will be saved:.
        /// </summary>
        public static string SelectDirectory_Description {
            get {
                return ResourceManager.GetString("SelectDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add metadata to files.
        /// </summary>
        public static string SettingsWindow_AddMetadata {
            get {
                return ResourceManager.GetString("SettingsWindow_AddMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow duplicate video entries.
        /// </summary>
        public static string SettingsWindow_AllowDuplicates {
            get {
                return ResourceManager.GetString("SettingsWindow_AllowDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingsWindow_Appearance {
            get {
                return ResourceManager.GetString("SettingsWindow_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Download Archive.
        /// </summary>
        public static string SettingsWindow_ArchiveFile {
            get {
                return ResourceManager.GetString("SettingsWindow_ArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates at startup.
        /// </summary>
        public static string SettingsWindow_AutoCheckUpdates {
            get {
                return ResourceManager.GetString("SettingsWindow_AutoCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string SettingsWindow_Binaries {
            get {
                return ResourceManager.GetString("SettingsWindow_Binaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string SettingsWindow_CheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsWindow_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string SettingsWindow_CheckingForUpdates {
            get {
                return ResourceManager.GetString("SettingsWindow_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default download format:.
        /// </summary>
        public static string SettingsWindow_DefaultFormat {
            get {
                return ResourceManager.GetString("SettingsWindow_DefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string SettingsWindow_Download {
            get {
                return ResourceManager.GetString("SettingsWindow_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Download Folder.
        /// </summary>
        public static string SettingsWindow_DownloadFolder {
            get {
                return ResourceManager.GetString("SettingsWindow_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Options.
        /// </summary>
        public static string SettingsWindow_DownloadOptions {
            get {
                return ResourceManager.GetString("SettingsWindow_DownloadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg.
        /// </summary>
        public static string SettingsWindow_Ffmpeg {
            get {
                return ResourceManager.GetString("SettingsWindow_Ffmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string SettingsWindow_Filename {
            get {
                return ResourceManager.GetString("SettingsWindow_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsWindow_General {
            get {
                return ResourceManager.GetString("SettingsWindow_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum concurrent downloads.
        /// </summary>
        public static string SettingsWindow_MaxProcesses {
            get {
                return ResourceManager.GetString("SettingsWindow_MaxProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing files.
        /// </summary>
        public static string SettingsWindow_OverwriteFiles {
            get {
                return ResourceManager.GetString("SettingsWindow_OverwriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the executable on your PC.
        /// </summary>
        public static string SettingsWindow_Path_ToolTip {
            get {
                return ResourceManager.GetString("SettingsWindow_Path_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download best quality and convert.
        /// </summary>
        public static string SettingsWindow_PreferRecoding {
            get {
                return ResourceManager.GetString("SettingsWindow_PreferRecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string SettingsWindow_Proxy {
            get {
                return ResourceManager.GetString("SettingsWindow_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL.
        /// </summary>
        public static string SettingsWindow_ProxyUrl {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict filename to ASCII characters.
        /// </summary>
        public static string SettingsWindow_RestrictFilenames {
            get {
                return ResourceManager.GetString("SettingsWindow_RestrictFilenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all available formats.
        /// </summary>
        public static string SettingsWindow_ShowAllFormats {
            get {
                return ResourceManager.GetString("SettingsWindow_ShowAllFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme:.
        /// </summary>
        public static string SettingsWindow_Theme {
            get {
                return ResourceManager.GetString("SettingsWindow_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string SettingsWindow_Version {
            get {
                return ResourceManager.GetString("SettingsWindow_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download List.
        /// </summary>
        public static string SettingsWindow_VideoList {
            get {
                return ResourceManager.GetString("SettingsWindow_VideoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube-dl.
        /// </summary>
        public static string SettingsWindow_YoutubeDL {
            get {
                return ResourceManager.GetString("SettingsWindow_YoutubeDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled &quot;{0}&quot;..
        /// </summary>
        public static string Video_DownloadCancelled {
            get {
                return ResourceManager.GetString("Video_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download &quot;{0}&quot;..
        /// </summary>
        public static string Video_DownloadFailed {
            get {
                return ResourceManager.GetString("Video_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished &quot;{0}&quot;..
        /// </summary>
        public static string Video_DownloadFinished {
            get {
                return ResourceManager.GetString("Video_DownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &quot;{0}&quot;....
        /// </summary>
        public static string Video_DownloadStarting {
            get {
                return ResourceManager.GetString("Video_DownloadStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already existent. Item skipped..
        /// </summary>
        public static string VideoEntry_AlreadyDownloaded {
            get {
                return ResourceManager.GetString("VideoEntry_AlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        public static string VideoEntry_Converting {
            get {
                return ResourceManager.GetString("VideoEntry_Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Video URL.
        /// </summary>
        public static string VideoEntry_CopyUrl {
            get {
                return ResourceManager.GetString("VideoEntry_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download progress of current file.
        /// </summary>
        public static string VideoEntry_CurrentProgress {
            get {
                return ResourceManager.GetString("VideoEntry_CurrentProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string VideoEntry_Download {
            get {
                return ResourceManager.GetString("VideoEntry_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string VideoEntry_Downloading {
            get {
                return ResourceManager.GetString("VideoEntry_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current download rate.
        /// </summary>
        public static string VideoEntry_DownloadSpeed {
            get {
                return ResourceManager.GetString("VideoEntry_DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        public static string VideoEntry_Finished {
            get {
                return ResourceManager.GetString("VideoEntry_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Browser.
        /// </summary>
        public static string VideoEntry_OpenInBrowser {
            get {
                return ResourceManager.GetString("VideoEntry_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string VideoEntry_Play {
            get {
                return ResourceManager.GetString("VideoEntry_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist - {0} Videos.
        /// </summary>
        public static string VideoEntry_Playlist {
            get {
                return ResourceManager.GetString("VideoEntry_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing....
        /// </summary>
        public static string VideoEntry_PreProcessing {
            get {
                return ResourceManager.GetString("VideoEntry_PreProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Video.
        /// </summary>
        public static string VideoEntry_Reload {
            get {
                return ResourceManager.GetString("VideoEntry_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected remaining time for current file.
        /// </summary>
        public static string VideoEntry_RemainingTime {
            get {
                return ResourceManager.GetString("VideoEntry_RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Video.
        /// </summary>
        public static string VideoEntry_Remove {
            get {
                return ResourceManager.GetString("VideoEntry_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In Folder.
        /// </summary>
        public static string VideoEntry_ShowInFolder {
            get {
                return ResourceManager.GetString("VideoEntry_ShowInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Information.
        /// </summary>
        public static string VideoEntry_ShowInformation {
            get {
                return ResourceManager.GetString("VideoEntry_ShowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total download size of current file.
        /// </summary>
        public static string VideoEntry_TotalDownloadSize {
            get {
                return ResourceManager.GetString("VideoEntry_TotalDownloadSize", resourceCulture);
            }
        }
    }
}
