//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vividl.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vividl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to AVI.
        /// </summary>
        public static string DownloadOption_AVI {
            get {
                return ResourceManager.GetString("DownloadOption_AVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best Direct Download.
        /// </summary>
        public static string DownloadOption_Best {
            get {
                return ResourceManager.GetString("DownloadOption_Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to M4A.
        /// </summary>
        public static string DownloadOption_M4A {
            get {
                return ResourceManager.GetString("DownloadOption_M4A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merge to MKV.
        /// </summary>
        public static string DownloadOption_MKV {
            get {
                return ResourceManager.GetString("DownloadOption_MKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to MP3.
        /// </summary>
        public static string DownloadOption_MP3 {
            get {
                return ResourceManager.GetString("DownloadOption_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to MP4.
        /// </summary>
        public static string DownloadOption_MP4 {
            get {
                return ResourceManager.GetString("DownloadOption_MP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to Ogg Vorbis.
        /// </summary>
        public static string DownloadOption_Vorbis {
            get {
                return ResourceManager.GetString("DownloadOption_Vorbis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to WAV.
        /// </summary>
        public static string DownloadOption_WAV {
            get {
                return ResourceManager.GetString("DownloadOption_WAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to WebM.
        /// </summary>
        public static string DownloadOption_Webm {
            get {
                return ResourceManager.GetString("DownloadOption_Webm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear Output.
        /// </summary>
        public static string DownloadOutputWindow_ClearOutput {
            get {
                return ResourceManager.GetString("DownloadOutputWindow_ClearOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy Output.
        /// </summary>
        public static string DownloadOutputWindow_CopyOutput {
            get {
                return ResourceManager.GetString("DownloadOutputWindow_CopyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download Output.
        /// </summary>
        public static string DownloadOutputWindow_Title {
            get {
                return ResourceManager.GetString("DownloadOutputWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download Format.
        /// </summary>
        public static string FetchWindow_DownloadFormat {
            get {
                return ResourceManager.GetString("FetchWindow_DownloadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download playlist if available.
        /// </summary>
        public static string FetchWindow_DownloadPlaylist {
            get {
                return ResourceManager.GetString("FetchWindow_DownloadPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Video URLs in separate lines.
        /// </summary>
        public static string FetchWindow_EnterUrls {
            get {
                return ResourceManager.GetString("FetchWindow_EnterUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start download immediately.
        /// </summary>
        public static string FetchWindow_ImmediateDownload {
            get {
                return ResourceManager.GetString("FetchWindow_ImmediateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string FetchWindow_Options {
            get {
                return ResourceManager.GetString("FetchWindow_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string FetchWindow_Password {
            get {
                return ResourceManager.GetString("FetchWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string FetchWindow_Settings {
            get {
                return ResourceManager.GetString("FetchWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication.
        /// </summary>
        public static string FetchWindow_TabAuthentication {
            get {
                return ResourceManager.GetString("FetchWindow_TabAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string FetchWindow_TabGeneral {
            get {
                return ResourceManager.GetString("FetchWindow_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string FetchWindow_Username {
            get {
                return ResourceManager.GetString("FetchWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video Password.
        /// </summary>
        public static string FetchWindow_VideoPassword {
            get {
                return ResourceManager.GetString("FetchWindow_VideoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This video has already been fetched to the download list.
        ///To allow duplicates, go to Options -&gt; Settings..
        /// </summary>
        public static string MainWindow_AlreadyFetched {
            get {
                return ResourceManager.GetString("MainWindow_AlreadyFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fetching {0} videos failed:.
        /// </summary>
        public static string MainWindow_CountFailedFetches {
            get {
                return ResourceManager.GetString("MainWindow_CountFailedFetches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download Folder.
        /// </summary>
        public static string MainWindow_DownloadFolder {
            get {
                return ResourceManager.GetString("MainWindow_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please make sure the given URL is valid..
        /// </summary>
        public static string MainWindow_FetchFailed_General {
            get {
                return ResourceManager.GetString("MainWindow_FetchFailed_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to fetch video.
        /// </summary>
        public static string MainWindow_FetchFailed_Title {
            get {
                return ResourceManager.GetString("MainWindow_FetchFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _File.
        /// </summary>
        public static string MainWindow_HeaderFile {
            get {
                return ResourceManager.GetString("MainWindow_HeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Options.
        /// </summary>
        public static string MainWindow_HeaderOptions {
            get {
                return ResourceManager.GetString("MainWindow_HeaderOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Videos.
        /// </summary>
        public static string MainWindow_HeaderVideos {
            get {
                return ResourceManager.GetString("MainWindow_HeaderVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new videos by pasting or importing URLs..
        /// </summary>
        public static string MainWindow_ListEmpty {
            get {
                return ResourceManager.GetString("MainWindow_ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _About.
        /// </summary>
        public static string MainWindow_MenuAbout {
            get {
                return ResourceManager.GetString("MainWindow_MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Add New Videos.
        /// </summary>
        public static string MainWindow_MenuAdd {
            get {
                return ResourceManager.GetString("MainWindow_MenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Cancel All Downloads.
        /// </summary>
        public static string MainWindow_MenuCancelAll {
            get {
                return ResourceManager.GetString("MainWindow_MenuCancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Clear Download List.
        /// </summary>
        public static string MainWindow_MenuClearList {
            get {
                return ResourceManager.GetString("MainWindow_MenuClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Download All Videos.
        /// </summary>
        public static string MainWindow_MenuDownloadAll {
            get {
                return ResourceManager.GetString("MainWindow_MenuDownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Exit.
        /// </summary>
        public static string MainWindow_MenuExit {
            get {
                return ResourceManager.GetString("MainWindow_MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Export Video Links.
        /// </summary>
        public static string MainWindow_MenuExport {
            get {
                return ResourceManager.GetString("MainWindow_MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Import Video Links.
        /// </summary>
        public static string MainWindow_MenuImport {
            get {
                return ResourceManager.GetString("MainWindow_MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Output Window.
        /// </summary>
        public static string MainWindow_MenuOutputWindow {
            get {
                return ResourceManager.GetString("MainWindow_MenuOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Paste Video Link.
        /// </summary>
        public static string MainWindow_MenuPaste {
            get {
                return ResourceManager.GetString("MainWindow_MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Remove.
        /// </summary>
        public static string MainWindow_MenuRemove {
            get {
                return ResourceManager.GetString("MainWindow_MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All _Finished Downloads.
        /// </summary>
        public static string MainWindow_MenuRemoveFinished {
            get {
                return ResourceManager.GetString("MainWindow_MenuRemoveFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All _Unavailable Downloads.
        /// </summary>
        public static string MainWindow_MenuRemoveUnavailable {
            get {
                return ResourceManager.GetString("MainWindow_MenuRemoveUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Download _Folder....
        /// </summary>
        public static string MainWindow_MenuSelectFolder {
            get {
                return ResourceManager.GetString("MainWindow_MenuSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Settings.
        /// </summary>
        public static string MainWindow_MenuSettings {
            get {
                return ResourceManager.GetString("MainWindow_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string MainWindow_OpenFolder {
            get {
                return ResourceManager.GetString("MainWindow_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed:.
        /// </summary>
        public static string MainWindow_StatusFailed {
            get {
                return ResourceManager.GetString("MainWindow_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In Process:.
        /// </summary>
        public static string MainWindow_StatusInProcess {
            get {
                return ResourceManager.GetString("MainWindow_StatusInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successful:.
        /// </summary>
        public static string MainWindow_StatusSucceeded {
            get {
                return ResourceManager.GetString("MainWindow_StatusSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creator:.
        /// </summary>
        public static string MetadataWindow_Creator {
            get {
                return ResourceManager.GetString("MetadataWindow_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string MetadataWindow_Description {
            get {
                return ResourceManager.GetString("MetadataWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string MetadataWindow_Details {
            get {
                return ResourceManager.GetString("MetadataWindow_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration:.
        /// </summary>
        public static string MetadataWindow_Duration {
            get {
                return ResourceManager.GetString("MetadataWindow_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link.
        /// </summary>
        public static string MetadataWindow_Link {
            get {
                return ResourceManager.GetString("MetadataWindow_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source:.
        /// </summary>
        public static string MetadataWindow_Source {
            get {
                return ResourceManager.GetString("MetadataWindow_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploaded:.
        /// </summary>
        public static string MetadataWindow_UploadDate {
            get {
                return ResourceManager.GetString("MetadataWindow_UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploader:.
        /// </summary>
        public static string MetadataWindow_Uploader {
            get {
                return ResourceManager.GetString("MetadataWindow_Uploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Views:.
        /// </summary>
        public static string MetadataWindow_Views {
            get {
                return ResourceManager.GetString("MetadataWindow_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change.
        /// </summary>
        public static string PathSelectionControl_Change {
            get {
                return ResourceManager.GetString("PathSelectionControl_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy Playlist URL.
        /// </summary>
        public static string PlaylistEntry_CopyUrl {
            get {
                return ResourceManager.GetString("PlaylistEntry_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the directory where the downloaded videos will be saved:.
        /// </summary>
        public static string SelectDirectory_Description {
            get {
                return ResourceManager.GetString("SelectDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add metadata to files.
        /// </summary>
        public static string SettingsWindow_AddMetadata {
            get {
                return ResourceManager.GetString("SettingsWindow_AddMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow duplicate video entries.
        /// </summary>
        public static string SettingsWindow_AllowDuplicates {
            get {
                return ResourceManager.GetString("SettingsWindow_AllowDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        public static string SettingsWindow_Appearance {
            get {
                return ResourceManager.GetString("SettingsWindow_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use Download Archive.
        /// </summary>
        public static string SettingsWindow_ArchiveFile {
            get {
                return ResourceManager.GetString("SettingsWindow_ArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically check for updates at startup.
        /// </summary>
        public static string SettingsWindow_AutoCheckUpdates {
            get {
                return ResourceManager.GetString("SettingsWindow_AutoCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application.
        /// </summary>
        public static string SettingsWindow_Binaries {
            get {
                return ResourceManager.GetString("SettingsWindow_Binaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check For Updates.
        /// </summary>
        public static string SettingsWindow_CheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsWindow_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking for updates....
        /// </summary>
        public static string SettingsWindow_CheckingForUpdates {
            get {
                return ResourceManager.GetString("SettingsWindow_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default download format:.
        /// </summary>
        public static string SettingsWindow_DefaultFormat {
            get {
                return ResourceManager.GetString("SettingsWindow_DefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string SettingsWindow_Download {
            get {
                return ResourceManager.GetString("SettingsWindow_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video Download Folder.
        /// </summary>
        public static string SettingsWindow_DownloadFolder {
            get {
                return ResourceManager.GetString("SettingsWindow_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download Options.
        /// </summary>
        public static string SettingsWindow_DownloadOptions {
            get {
                return ResourceManager.GetString("SettingsWindow_DownloadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ffmpeg.
        /// </summary>
        public static string SettingsWindow_Ffmpeg {
            get {
                return ResourceManager.GetString("SettingsWindow_Ffmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filename.
        /// </summary>
        public static string SettingsWindow_Filename {
            get {
                return ResourceManager.GetString("SettingsWindow_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string SettingsWindow_General {
            get {
                return ResourceManager.GetString("SettingsWindow_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum concurrent downloads.
        /// </summary>
        public static string SettingsWindow_MaxProcesses {
            get {
                return ResourceManager.GetString("SettingsWindow_MaxProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overwrite existing files.
        /// </summary>
        public static string SettingsWindow_OverwriteFiles {
            get {
                return ResourceManager.GetString("SettingsWindow_OverwriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location of the executable on your PC.
        /// </summary>
        public static string SettingsWindow_Path_ToolTip {
            get {
                return ResourceManager.GetString("SettingsWindow_Path_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download best quality and convert.
        /// </summary>
        public static string SettingsWindow_PreferRecoding {
            get {
                return ResourceManager.GetString("SettingsWindow_PreferRecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy.
        /// </summary>
        public static string SettingsWindow_Proxy {
            get {
                return ResourceManager.GetString("SettingsWindow_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy URL.
        /// </summary>
        public static string SettingsWindow_ProxyUrl {
            get {
                return ResourceManager.GetString("SettingsWindow_ProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restrict filename to ASCII characters.
        /// </summary>
        public static string SettingsWindow_RestrictFilenames {
            get {
                return ResourceManager.GetString("SettingsWindow_RestrictFilenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show all available formats.
        /// </summary>
        public static string SettingsWindow_ShowAllFormats {
            get {
                return ResourceManager.GetString("SettingsWindow_ShowAllFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application Theme:.
        /// </summary>
        public static string SettingsWindow_Theme {
            get {
                return ResourceManager.GetString("SettingsWindow_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version:.
        /// </summary>
        public static string SettingsWindow_Version {
            get {
                return ResourceManager.GetString("SettingsWindow_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download List.
        /// </summary>
        public static string SettingsWindow_VideoList {
            get {
                return ResourceManager.GetString("SettingsWindow_VideoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на youtube-dl.
        /// </summary>
        public static string SettingsWindow_YoutubeDL {
            get {
                return ResourceManager.GetString("SettingsWindow_YoutubeDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancelled &quot;{0}&quot;..
        /// </summary>
        public static string Video_DownloadCancelled {
            get {
                return ResourceManager.GetString("Video_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to download &quot;{0}&quot;..
        /// </summary>
        public static string Video_DownloadFailed {
            get {
                return ResourceManager.GetString("Video_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished &quot;{0}&quot;..
        /// </summary>
        public static string Video_DownloadFinished {
            get {
                return ResourceManager.GetString("Video_DownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading &quot;{0}&quot;....
        /// </summary>
        public static string Video_DownloadStarting {
            get {
                return ResourceManager.GetString("Video_DownloadStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Already existent. Item skipped..
        /// </summary>
        public static string VideoEntry_AlreadyDownloaded {
            get {
                return ResourceManager.GetString("VideoEntry_AlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converting....
        /// </summary>
        public static string VideoEntry_Converting {
            get {
                return ResourceManager.GetString("VideoEntry_Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy Video URL.
        /// </summary>
        public static string VideoEntry_CopyUrl {
            get {
                return ResourceManager.GetString("VideoEntry_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download progress of current file.
        /// </summary>
        public static string VideoEntry_CurrentProgress {
            get {
                return ResourceManager.GetString("VideoEntry_CurrentProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string VideoEntry_Download {
            get {
                return ResourceManager.GetString("VideoEntry_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading....
        /// </summary>
        public static string VideoEntry_Downloading {
            get {
                return ResourceManager.GetString("VideoEntry_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current download rate.
        /// </summary>
        public static string VideoEntry_DownloadSpeed {
            get {
                return ResourceManager.GetString("VideoEntry_DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished..
        /// </summary>
        public static string VideoEntry_Finished {
            get {
                return ResourceManager.GetString("VideoEntry_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open In Browser.
        /// </summary>
        public static string VideoEntry_OpenInBrowser {
            get {
                return ResourceManager.GetString("VideoEntry_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play.
        /// </summary>
        public static string VideoEntry_Play {
            get {
                return ResourceManager.GetString("VideoEntry_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playlist - {0} Videos.
        /// </summary>
        public static string VideoEntry_Playlist {
            get {
                return ResourceManager.GetString("VideoEntry_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing....
        /// </summary>
        public static string VideoEntry_PreProcessing {
            get {
                return ResourceManager.GetString("VideoEntry_PreProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload Video.
        /// </summary>
        public static string VideoEntry_Reload {
            get {
                return ResourceManager.GetString("VideoEntry_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expected remaining time for current file.
        /// </summary>
        public static string VideoEntry_RemainingTime {
            get {
                return ResourceManager.GetString("VideoEntry_RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Video.
        /// </summary>
        public static string VideoEntry_Remove {
            get {
                return ResourceManager.GetString("VideoEntry_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show In Folder.
        /// </summary>
        public static string VideoEntry_ShowInFolder {
            get {
                return ResourceManager.GetString("VideoEntry_ShowInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Information.
        /// </summary>
        public static string VideoEntry_ShowInformation {
            get {
                return ResourceManager.GetString("VideoEntry_ShowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total download size of current file.
        /// </summary>
        public static string VideoEntry_TotalDownloadSize {
            get {
                return ResourceManager.GetString("VideoEntry_TotalDownloadSize", resourceCulture);
            }
        }
    }
}
